### ISSUE TITLE
2D Wavelet Faktor 4

### ISSUE THREAD

**Issue by cocreature** [phiresky/algo2-summary#3]
Ich bin zu faul für einen PR, aber der Faktor 4 da ist Bullshit. Den Faktor 4 brauchst du um den Faktor 1/4 auszugleichen, nicht stattdessen.

**Comment by phiresky** [comment]
ja aber passt doch?

**Comment by phiresky** [comment]
@TiFu

**Comment by cocreature** [comment]
„jedoch mit Faktor 4 statt 0.25“ Das passt nicht. Entweder du nimmst gar keinen Faktor oder du nimmst beide damit wieder 1 rauskommt.

**Comment by TiFu** [comment]
oh. ja stimmt
danke
